### ISSUE TITLE
[question] about docker-compose file for Standardnotes

### ISSUE THREAD

**Issue by BobWs** [eric-pierce/Personal-Cloud#1]
Hi,
In your docker-compose.yml file you have the following entry:
```
  snsync:
    container_name: snsync
    image: standardnotes/syncing-server-js:$SNSYNC_VERSION
```
How did you reference/map the image version to the docker-compose.yml?
I mean `$SNSYNC_VERSION` must be mapped to some sort of file or so otherwise it will not work. I have tried it your way for the standnotes containers but I'm keep getting an error the image version isn't specified. 

Can you please share how you did that?

**Comment by eric-pierce** [comment]
Hey @BobWs - I set up the version variables in my .env file which I use for all environment variables - it’s a little clunky to have to update them to match the standalone repo but that’s what I’ve been doing. I may write a cron job to automatically update the env file each day at some point.

**Comment by BobWs** [comment]
> Hey @BobWs - I set up the version variables in my .env file which I use for all environment variables - it’s a little clunky to have to update them to match the standalone repo but that’s what I’ve been doing. I may write a cron job to automatically update the env file each day at some point.

Okay thank for sharing, I will give it a try!

**Comment by BobWs** [comment]
> > Hey @BobWs - I set up the version variables in my .env file which I use for all environment variables - it’s a little clunky to have to update them to match the standalone repo but that’s what I’ve been doing. I may write a cron job to automatically update the env file each day at some point.
> 
> Okay thank for sharing, I will give it a try!

Hi **@eric-pierce** -  Unfortunately it isn't working for me the way you suggested. Don't know what I'm doing wrong. 
Maybe you could take a look at it for me?

This is my docker-compose file 

```
version: '3.8'

services:
  syncing-server-js:
    image: standardnotes/syncing-server-js:${SYNC_VERSION}
    container_name: standardnotes-syncing-server
    depends_on:
      - db
      - cache
    entrypoint: [
      "./wait-for.sh", "db", "3306",
      "./wait-for.sh", "cache", "6379",
      "./docker/entrypoint.sh", "start-web"
    ]
    env_file: .env
    environment:
      PORT: 3000
    restart: always
    networks:
      - standardnotes_standalone

  syncing-server-js-worker:
    image: standardnotes/syncing-server-js:${SYNC_VERSION}
    container_name: standardnotes-worker
    depends_on:
      - db
      - cache
      - syncing-server-js
    entrypoint: [
      "./wait-for.sh", "db", "3306",
      "./wait-for.sh", "cache", "6379",
      "./wait-for.sh", "syncing-server-js", "3000",
       "./docker/entrypoint.sh", "start-worker"
    ]
    env_file: .env
    environment:
      PORT: 3000
    restart: always
    networks:
      - standardnotes_standalone

  api-gateway:
    image: standardnotes/api-gateway:${API_VERSION}
    container_name: standardnotes-api-gateway
    depends_on:
      - auth
      - syncing-server-js
    env_file: api-gateway.env
    ports:
      - ${EXPOSED_PORT}:3000
    environment:
      PORT: 3000
      AUTH_JWT_SECRET: '${AUTH_JWT_SECRET}'
    entrypoint: [
      "./wait-for.sh", "auth", "3000",
      "./wait-for.sh", "syncing-server-js", "3000",
      "./docker/entrypoint.sh", "start-web"
    ]
    restart: always
    networks:
      - standardnotes_standalone

  auth:
    image: standardnotes/auth:${AUTH_VERSION}
    container_name: standardnotes-auth
    depends_on:
      - db
      - cache
      - syncing-server-js
    entrypoint: [
      "./wait-for.sh", "db", "3306",
      "./wait-for.sh", "cache", "6379",
      "./wait-for.sh", "syncing-server-js", "3000",
      "./docker/entrypoint.sh", "start-web"
    ]
    env_file: auth.env
    environment:
      PORT: 3000
      DB_HOST: '${DB_HOST}'
      DB_REPLICA_HOST: '${DB_REPLICA_HOST}'
      DB_PORT: '${DB_PORT}'
      DB_DATABASE: '${DB_DATABASE}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_DEBUG_LEVEL: '${DB_DEBUG_LEVEL}'
      DB_MIGRATIONS_PATH: '${DB_MIGRATIONS_PATH}'
      REDIS_URL: '${REDIS_URL}'
      AUTH_JWT_SECRET: '${AUTH_JWT_SECRET}'
    restart: always
    networks:
      - standardnotes_standalone

  auth-worker:
    image: standardnotes/auth:${AUTH_VERSION}
    container_name: standardnotes-auth-worker
    depends_on:
      - db
      - cache
      - auth
    entrypoint: [
      "./wait-for.sh", "db", "3306",
      "./wait-for.sh", "cache", "6379",
      "./wait-for.sh", "auth", "3000",
      "./docker/entrypoint.sh", "start-worker"
    ]
    env_file: auth.env
    environment:
      PORT: 3000
      DB_HOST: '${DB_HOST}'
      DB_REPLICA_HOST: '${DB_REPLICA_HOST}'
      DB_PORT: '${DB_PORT}'
      DB_DATABASE: '${DB_DATABASE}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_DEBUG_LEVEL: '${DB_DEBUG_LEVEL}'
      DB_MIGRATIONS_PATH: '${DB_MIGRATIONS_PATH}'
      REDIS_URL: '${REDIS_URL}'
      AUTH_JWT_SECRET: '${AUTH_JWT_SECRET}'
    restart: always
    networks:
      - standardnotes_standalone

  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
    ports:
      - 3306:3306/tcp
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - /docker/mariadb/vmdb/db:/var/lib/mysql:rw
      -/docker/mariadb/vmdb/db/import:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - standardnotes_standalone

  cache:
    image: redis:latest
    container_name: redis
    volumes:
      - /docker/redis/data:/data
    ports:
      - 6379:6379/tcp
    restart: always
    networks:
      - standardnotes_standalone

networks:
  standardnotes_standalone:
    name: standardnotes_standalone
```

These are parts of my `env` files where I put the variables :
```
#########################################
# Version syncing-server-js
#########################################

SYNC_VERSION=1.39.0
```
```
#########################################
# Version api-gateway
#########################################

API_VERSION=1.24.0
```
```
#########################################
# Version auth
#########################################

AUTH_VERSION=1.18.0
```
And this is the error message I'm getting in terminal after I run `docker-compose -p "standardnotes" up -d`
```
WARNING: The API_VERSION variable is not set. Defaulting to a blank string.
WARNING: The AUTH_VERSION variable is not set. Defaulting to a blank string.
ERROR: no such image: standardnotes/auth:: invalid reference format
```
